name: CI

on: push

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    env:
      # The test private keys are well-known and used as an example only
      ARB_PRIVATE_KEY: '0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d'
      ARB_TESTNET_PRIVATE_KEY: '0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d'
    steps:
      - uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm i

      - name: npx hardhat compile
        run: npx hardhat compile

      - name: npx hardhat test
        run: npx hardhat test
