name: CI

on: push

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm i

      - name: npx hardhat compile
        run: npx hardhat compile

      - name: npx hardhat test
        run: npx hardhat test
